
mybatis:
  mapper-locations: classpath:com/geekgame/demo/dao/*.xml

server:
  port: 8083

worker:
  id: 2

logging:
  level:
    root: info

spring:
  datasource:
    password: xxxxxxxx
    url: xxxxxxxx
    username: root
    type: xxxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

  redis:
    host: xxx.xxx.xxx.xxx
    password: xxxxxxxx
    port: 6379

  application:
    name: geekgame-item-app

  cloud:
    nacos:
      discovery:
        server-addr: xxx.xxx.xxx:xxxx

dubbo:
  cloud:
    subscribed-services:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.geekgame.demo.service.impl

seata:
  enabled: true
  application-id: geekgame-item-app
  tx-service-group: default_tx_group
  enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: xxx.xxx.xxx.xxx:xxxx
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
      data-id: seata.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: xxx.xxx.xxx.xxx:xxxx
      group: SEATA_GROUP
      namespace:
      username: "nacos"
      password: "nacos"


